dist: xenial
language: cpp
compiler: clang
addons:
  apt:
    packages:
    - libboost-test-dev
    - doxygen
    - graphviz
script:
- cmake .
- cmake --build .
- cmake --build . --target test
- cmake --build . --target package
- doxygen
deploy:
  - provider: script
    skip_cleanup: true
    script:
    - curl -f -T bulk-1.2.$TRAVIS_BUILD_NUMBER-Linux.deb -uboris-ulyanov:$BINTRAY_API_KEY "https://api.bintray.com/content/boris-ulyanov/otus-cpp/homework/$TRAVIS_BUILD_NUMBER/bulk-1.2.$TRAVIS_BUILD_NUMBER-Linux.deb;deb_distribution=xenial;deb_component=main;deb_architecture=amd64;publish=1"

  - provider: pages
    skip_cleanup: true
    github_token: $GITHUB_TOKEN
    keep_history: true
    local_dir: doc/html
